[build-system]
requires = ["setuptools >= 68.2.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kestrel_datasource_stixshifter"
version = "1.8.1"
description = "Kestrel STIX-shifter Datasource Interface"
readme = "README.rst"
requires-python = ">=3.8"
license = {text = "Apache 2.0 License"}
maintainers = [
    {name = "Xiaokui Shu", email = "xiaokui.shu@ibm.com"},
    {name = "Paul Coccoli", email = "pcoccoli@us.ibm.com"},
]
keywords = [
    "kestrel",
    "datasource",
    "interface",
    "STIX-shifter",
]
classifiers = [
    "Topic :: Security",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
]

dependencies = [
    "kestrel_core>=1.8.1",
    "lxml>=4.9.3",
    "requests>=2.31.0",
    "nest-asyncio>=1.5.8",
    "stix-shifter==6.2.2",
    "stix-shifter-utils==6.2.2",
]

[project.optional-dependencies]
test = [
    "pytest",
    "stix-shifter-modules-elastic-ecs",
]

[project.urls]
Homepage = "https://github.com/opencybersecurityalliance/kestrel-lang"
Documentation = "https://kestrel.readthedocs.io/"
Repository = "https://github.com/opencybersecurityalliance/kestrel-lang.git"

[project.scripts]
stix-shifter-diag = "kestrel_datasource_stixshifter.cli:stix_shifter_diag"
